#!/usr/bin/env bash
# =============================================================================
# TrustLend – Soroban Contract Deployment Script
# =============================================================================
# Prerequisites:
#   1. Rust + wasm32 target:
#        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
#        rustup target add wasm32-unknown-unknown
#   2. Stellar CLI ≥ 22:
#        cargo install --locked stellar-cli --features opt
#   3. Run:  stellar keys generate trustlend-admin --global
#            stellar keys use trustlend-admin
#            stellar keys address trustlend-admin   ← note your admin address
#   4. Fund on testnet:
#        curl "https://friendbot.stellar.org/?addr=<YOUR_ADMIN_ADDRESS>"
# =============================================================================

set -euo pipefail

NETWORK="testnet"
ADMIN_KEY="trustlend-admin"
ADMIN_ADDRESS=$(stellar keys address "$ADMIN_KEY")

echo "═══════════════════════════════════════════════════"
echo "  TrustLend Contract Deployment — Stellar Testnet"
echo "  Admin: $ADMIN_ADDRESS"
echo "═══════════════════════════════════════════════════"
echo ""

# ── Step 1: Build all contracts ───────────────────────────────────────────────

echo "▶ Building Rust contracts…"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR/.."   # contracts/ directory

stellar contract build

echo "✔ Build complete"
echo ""

# ── Step 2: Deploy contracts ─────────────────────────────────────────────────
# Order matters: Reputation + Escrow first (no deps), then Lending, then Default

echo "▶ Deploying BorrowerReputationContract…"
REPUTATION_ID=$(stellar contract deploy \
  --wasm target/wasm32v1-none/release/borrower_reputation.wasm \
  --network "$NETWORK" \
  --source "$ADMIN_KEY")
echo "  ✔ REPUTATION_CONTRACT_ID = $REPUTATION_ID"

echo ""
echo "▶ Deploying EscrowContract…"
ESCROW_ID=$(stellar contract deploy \
  --wasm target/wasm32v1-none/release/escrow.wasm \
  --network "$NETWORK" \
  --source "$ADMIN_KEY")
echo "  ✔ ESCROW_CONTRACT_ID = $ESCROW_ID"

echo ""
echo "▶ Deploying LendingContract…"
LENDING_ID=$(stellar contract deploy \
  --wasm target/wasm32v1-none/release/lending.wasm \
  --network "$NETWORK" \
  --source "$ADMIN_KEY")
echo "  ✔ LENDING_CONTRACT_ID = $LENDING_ID"

echo ""
echo "▶ Deploying DefaultManagementContract…"
DEFAULT_ID=$(stellar contract deploy \
  --wasm target/wasm32v1-none/release/default_management.wasm \
  --network "$NETWORK" \
  --source "$ADMIN_KEY")
echo "  ✔ DEFAULT_CONTRACT_ID = $DEFAULT_ID"

# ── Step 3: Initialise contracts ──────────────────────────────────────────────

echo ""
echo "▶ Initialising BorrowerReputationContract…"
stellar contract invoke \
  --id "$REPUTATION_ID" \
  --source "$ADMIN_KEY" \
  --network "$NETWORK" \
  -- initialize \
  --admin "$ADMIN_ADDRESS"

echo "▶ Initialising EscrowContract…"
stellar contract invoke \
  --id "$ESCROW_ID" \
  --source "$ADMIN_KEY" \
  --network "$NETWORK" \
  -- initialize \
  --admin "$ADMIN_ADDRESS"

echo "▶ Initialising LendingContract…"
stellar contract invoke \
  --id "$LENDING_ID" \
  --source "$ADMIN_KEY" \
  --network "$NETWORK" \
  -- initialize \
  --admin "$ADMIN_ADDRESS"

echo "▶ Initialising DefaultManagementContract (insurance_balance = 0)…"
stellar contract invoke \
  --id "$DEFAULT_ID" \
  --source "$ADMIN_KEY" \
  --network "$NETWORK" \
  -- initialize \
  --admin "$ADMIN_ADDRESS" \
  --initial_insurance_balance 0

echo ""
echo "✔ All contracts initialised"

# ── Step 4: Generate TypeScript bindings ──────────────────────────────────────

BINDINGS_OUT="../../lib/contracts/generated"
mkdir -p "$BINDINGS_OUT"

echo ""
echo "▶ Generating TypeScript bindings…"

stellar contract bindings typescript \
  --network "$NETWORK" \
  --id "$REPUTATION_ID" \
  --output-dir "$BINDINGS_OUT/reputation"

stellar contract bindings typescript \
  --network "$NETWORK" \
  --id "$ESCROW_ID" \
  --output-dir "$BINDINGS_OUT/escrow"

stellar contract bindings typescript \
  --network "$NETWORK" \
  --id "$LENDING_ID" \
  --output-dir "$BINDINGS_OUT/lending"

stellar contract bindings typescript \
  --network "$NETWORK" \
  --id "$DEFAULT_ID" \
  --output-dir "$BINDINGS_OUT/default_management"

echo "  ✔ Bindings written to lib/contracts/generated/"

# ── Step 5: Write .env.local snippet ─────────────────────────────────────────

ENV_OUT="../../.env.contracts"
cat > "$ENV_OUT" <<EOF
# ── Soroban Contract IDs (generated by deploy.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")) ──
NEXT_PUBLIC_REPUTATION_CONTRACT_ID=$REPUTATION_ID
NEXT_PUBLIC_ESCROW_CONTRACT_ID=$ESCROW_ID
NEXT_PUBLIC_LENDING_CONTRACT_ID=$LENDING_ID
NEXT_PUBLIC_DEFAULT_CONTRACT_ID=$DEFAULT_ID
NEXT_PUBLIC_ADMIN_ADDRESS=$ADMIN_ADDRESS
EOF

echo ""
echo "═══════════════════════════════════════════════════"
echo "  Deployment complete!"
echo ""
echo "  Copy the values from .env.contracts into .env.local:"
echo "  cat .env.contracts >> .env.local"
echo ""
echo "  Contract IDs:"
echo "    Reputation  : $REPUTATION_ID"
echo "    Escrow      : $ESCROW_ID"
echo "    Lending     : $LENDING_ID"
echo "    Default Mgmt: $DEFAULT_ID"
echo "═══════════════════════════════════════════════════"
